### ISSUE TITLE
EPIC - Secure default configuration

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-idam#58]
```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-idam/issues/52
- [ ] https://github.com/defenseunicorns/uds-idam/issues/53
- [ ] https://github.com/defenseunicorns/uds-idam/issues/81
```

**Comment by adam-defenseunicorns** [comment]
Closing due to inactivity.

**Comment by adam-defenseunicorns** [comment]
Closing due to inactivity.
